spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

