spring:
  application:
    name: gateway

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  ignored-services: '*'
  ribbon:
    eager-load:
      enabled: true
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
  strip-prefix: false

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
